# Generated by Django 4.2.16 on 2024-10-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_staff_administrativestaff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='size',
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='size', to='base.size'),
        ),
    ]
