# Generated by Django 4.2.16 on 2024-10-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gallery_description_gallery_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, default='Default Gallery Description', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, default='Default Gallery Title', max_length=255, null=True),
        ),
    ]
