# Generated by Django 4.2.16 on 2024-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_clothes_size_clothes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballer',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
