# Generated by Django 4.2.16 on 2024-10-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_footballer_age_alter_footballer_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
